ALTER TYPE "SessionType" ADD VALUE 'WAITING_INCIDENT_CONFIRMATION';
ALTER TYPE "SessionType" ADD VALUE 'WAITING_INCIDENT_EDIT_SELECTION';
ALTER TYPE "SessionType" ADD VALUE 'WAITING_INCIDENT_EDIT_VALUE';
