ALTER TYPE "SessionType" ADD VALUE 'WAITING_REQUESTER_NAME';
ALTER TYPE "SessionType" ADD VALUE 'WAITING_REQUESTER_PHONE';
ALTER TYPE "SessionType" ADD VALUE 'WAITING_INCIDENT_SELECTION';

ALTER TABLE "Incident" ADD COLUMN "requesterPhone" TEXT;
